image_segmentation_node:
  ros__parameters:
    update_rate: 30.0    
    debug_view: true
  
    rgb_topic: "/k4a/rgb/image_raw"
    depth_topic: "/k4a/depth_to_rgb/image_raw"
    use_compressed: false

    # Alternative HSV ranges for common objects:
    # Green objects: hue_low: 40, hue_high: 80, sat_low: 50, sat_high: 255, val_low: 50, val_high: 255
    # Red objects: hue_low: 0, hue_high: 10, sat_low: 100, sat_high: 255, val_low: 100, val_high: 255
    # Blue objects: hue_low: 100, hue_high: 130, sat_low: 50, sat_high: 255, val_low: 50, val_high: 255

    hsv_hue_low: 0
    hsv_hue_high: 179
    hsv_saturation_low: 0
    hsv_saturation_high: 255
    hsv_value_low: 0
    hsv_value_high: 50

    depth_low: 250        
    depth_high: 800       
    depth_scale: 1.0      

    min_component_area: 1000
    connectivity: 8
    filter_largest_component: true

point_cloud_generator_node:
  ros__parameters:
    update_rate: 10.0
    depth_scale: 1000.0      
    voxel_size: 0.002      

    tf_x: 0.2
    tf_y: 0.0
    tf_z: 0.5
    tf_qx: 0.0
    tf_qy: 0.0
    tf_qz: 0.0
    tf_qw: 1.0
